### ISSUE TITLE
How to install the kernel on licheepi4a

### ISSUE THREAD

**Issue by dtometzki** [revyos/thead-kernel#13]
Hello together,

i can build the kernel as described in the documentation but on licheepi doesnt boot the kernel. 
Can you short describe the steps how to install ist ?

Regards
Damian

**Comment by nekorouter** [comment]
Hi,
Wiki page just updated with about how to build kernel, please check this one:

https://github.com/revyos/revyos/wiki/%E6%89%8B%E5%8A%A8%E7%BC%96%E8%AF%91%E5%86%85%E6%A0%B8---Maunally-Build-Kernel

Also you can check .github/workflows/kernel.yml in kernel repository, which is used for auto build kernel using Github Action.
