### ISSUE TITLE
modprobe: FATAL: Module binfmt_misc not found in directory /lib/modules/5.10.113-gbb4691fe5572

### ISSUE THREAD

**Issue by RevySR** [revyos/thead-kernel#18]
![image](https://github.com/revyos/thead-kernel/assets/13116853/7ecc2304-6e4d-47fa-a9ff-efb85276987c)

**Comment by xmzzz** [comment]
This is because the relevant CONFIG_BINFMT_MISC were not enabled. Let's enable it to fix this error.  #19
