### ISSUE TITLE
Commit 07167b855fa1f7 breaks USB storage device

### ISSUE THREAD

**Issue by dtometzki** [revyos/thead-kernel#32]
Hello together,

commit breaks my USB storage device doesnt work anymore

commit 07167b855fa1f7bae79cb617ca48846c1c3e2973 
Author: Lu Hui <luhui@sipeed.com>
Date:   Wed Aug 23 17:51:15 2023 +0800

    revyos_defconfig: enable usb uas driver

scsi 0:0:0:0: Direct-Access     AMicro   AM8180 NVME      1.00 PQ: 0 ANSI: 6

I didnt see the device under lsblk. 

Best regards
Daian

**Comment by 0x754C** [comment]
can you provide lsusb output?

I found two device in usb.ids:

```
1de1  Actions Microelectronics Co.
        1101  Generic Display Device (Mass storage mode)
        c101  Generic Display Device
```

we found some link for this device/chip on linux:

https://forums.raspberrypi.com/viewtopic.php?t=310993
https://www.draisberghof.de/usb_modeswitch/bb/viewtopic.php?t=2953
https://bugs.launchpad.net/ubuntu/+source/usb-modeswitch-data/+bug/1878921/comments/5
https://github.com/raspberrypi/linux/issues/4130

can you test your usb storage device on Linux PC ?

or you can blacklist uas module:

```
echo 'blacklist uas' >> /etc/modprobe.d/uas.conf
```

**Comment by dtometzki** [comment]
Hello,

without this config my USB storage works. 

Here the output from lsblk, lsusb and dmesg

- lsblk
NAME         MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
sda            8:0    0 931.5G  0 disk
mmcblk0      179:0    0 116.5G  0 disk
├─mmcblk0p1  179:1    0     2M  0 part
├─mmcblk0p2  179:2    0   500M  0 part /boot
└─mmcblk0p3  179:3    0   116G  0 part /
mmcblk0boot0 179:8    0     4M  1 disk
mmcblk0boot1 179:16   0     4M  1 disk

- lsusb:
Bus 002 Device 003: ID 1de1:e101 Actions Microelectronics Co. AM8180
Bus 002 Device 002: ID 2109:0817 VIA Labs, Inc. USB3.0 Hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 2109:8817 VIA Labs, Inc. USB Billboard Device
Bus 001 Device 002: ID 2109:2817 VIA Labs, Inc. USB2.0 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

- dmesg
11.676357] scsi 0:0:0:0: Direct-Access     AMicro   AM8180 NVME      1.00 PQ: 0 ANSI: 6
 17.701901] sd 0:0:0:0: [sda] Read Capacity(16) failed: Result: hostbyte=0x00 driverbyte=0x08
[   17.710640] sd 0:0:0:0: [sda] Sense Key : 0xb [current]
[   17.716359] sd 0:0:0:0: [sda] ASC=0x0 ASCQ=0x0
[   23.721558] sd 0:0:0:0: [sda] Read Capacity(10) failed: Result: hostbyte=0x00 driverbyte=0x08
[   23.730315] sd 0:0:0:0: [sda] Sense Key : 0xb [current]
[   23.736201] sd 0:0:0:0: [sda] ASC=0x0 ASCQ=0x0
[   27.741336] sd 0:0:0:0: [sda] 0 512-byte logical blocks: (0 B/0 B)
[   27.747712] sd 0:0:0:0: [sda] 0-byte physical blocks
[   31.751112] sd 0:0:0:0: [sda] Test WP failed, assume Write Enabled
[   33.751054] sd 0:0:0:0: [sda] Asking for cache data failed
[   33.756755] sd 0:0:0:0: [sda] Assuming drive cache: write through
[   35.843431] sd 0:0:0:0: [sda] 1953525168 512-byte logical blocks: (1.00 TB/932 GiB)
[   35.855046] sd 0:0:0:0: [sda] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[   35.865290] sd 0:0:0:0: [sda] Attached SCSI disk

-----------------------------
Output without UAS config: 

- lsblk
NAME         MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
sda            8:0    0 931.5G  0 disk
├─sda1         8:1    0 465.8G  0 part /home/damian/data
└─sda2         8:2    0 465.8G  0 part
mmcblk0      179:0    0 116.5G  0 disk
├─mmcblk0p1  179:1    0     2M  0 part
├─mmcblk0p2  179:2    0   500M  0 part /boot
└─mmcblk0p3  179:3    0   116G  0 part /
mmcblk0boot0 179:8    0     4M  1 disk
mmcblk0boot1 179:16   0     4M  1 disk
- lsusb
Bus 002 Device 003: ID 1de1:e101 Actions Microelectronics Co. AM8180
Bus 002 Device 002: ID 2109:0817 VIA Labs, Inc. USB3.0 Hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 2109:8817 VIA Labs, Inc. USB Billboard Device
Bus 001 Device 002: ID 2109:2817 VIA Labs, Inc. USB2.0 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

- dmesg
12.611557] scsi 0:0:0:0: Direct-Access     AMicro   AM8180 NVME      1.00 PQ: 0 ANSI: 6
[   12.627673] sd 0:0:0:0: [sda] 1953525168 512-byte logical blocks: (1.00 TB/932 GiB)
[   12.642622] sd 0:0:0:0: [sda] Write Protect is off
[   12.648364] sd 0:0:0:0: [sda] Mode Sense: 37 00 00 08
[   12.648987] sd 0:0:0:0: [sda] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
[   12.919478] light_dwmac_eth ffe7070000.ethernet end0: PHY [stmmac-0:01] driver [RTL8211F Gigabit Ethernet] (irq=POLL)
[   12.931645] alloc_contig_range: [3e4204, 3e4208) PFNs busy
[   12.949719] dwmac1000: Master AXI performs fixed burst length
[   12.955525] light_dwmac_eth ffe7070000.ethernet end0: No Safety Features support found
[   13.163660] light_dwmac_eth ffe7070000.ethernet end0: IEEE 1588-2008 Advanced Timestamp supported
[   13.179830] light_dwmac_eth ffe7070000.ethernet end0: configuring for phy/rgmii-id link mode
[   13.188417]  sda: sda1 sda2
[   13.197733] sd 0:0:0:0: [sda] Attached SCSI disk



Best regards
Damian

**Comment by dtometzki** [comment]
Hello,

i tested the device on my Linux Fedora box X86 with USB and USB-c both works. 
With Kernel Linux fedora 6.5.0

On my licheepi only works withou UAS and USB. USB-C doesnt work. 

Damian

**Comment by RevySR** [comment]
https://github.com/revyos/thead-kernel/pull/34
