### ISSUE TITLE
Need eBPF support in the RevyOS 5.10.x kernels

### ISSUE THREAD

**Issue by cp0613** [revyos/thead-kernel#69]
eBPF is a very useful technology in the Linux kernel and is the cornerstone of kernel observability. eBPF relies on features such as `k/u-probe` and `BTF`. Please help support some CONFIG listed below so that the front-end tools `bcc` and `bpftrace` can be used normally.
```
CONFIG_KPROBES=y
CONFIG_KPROBES_ON_FTRACE=y
CONFIG_KRETPROBES=y
CONFIG_BPF_JIT=y
CONFIG_CGROUP_BPF=y
CONFIG_KPROBE_EVENTS=y
CONFIG_IKHEADERS=y
CONFIG_KALLSYMS_ALL=y
CONFIG_DEBUG_INFO_BTF=y
CONFIG_CGROUP_SCHED=y
CONFIG_FAIR_GROUP_SCHED=y
```

**Comment by RevySR** [comment]
https://github.com/revyos/thead-kernel/pull/70
